<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => '2017-12-28 08:20:19',
                'updated_at' => '2017-12-28 08:20:19',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 3,
            'model' => 'Y5 2017 (สีเทา)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 3990,
                'type_sn' => 1,
                'barcode' => '6901443167029',
                'image' => '/assets/images/products/product-1.jpg',
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => '2017-12-28 08:21:55',
                'updated_at' => '2017-12-28 08:21:55',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 3,
            'model' => 'Y5 2017 (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 3990,
                'type_sn' => 0,
                'barcode' => '6901443167012',
                'image' => '/assets/images/products/product-2.jpg',
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => '2017-12-28 08:26:43',
                'updated_at' => '2017-12-28 08:26:43',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 3,
            'model' => 'Y3 2017 (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 3290,
                'type_sn' => 1,
                'barcode' => '6901443181711',
                'image' => '/assets/images/products/product-3.jpg',
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => '2017-12-28 08:28:18',
                'updated_at' => '2017-12-28 08:32:32',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 3,
            'model' => 'Y3 2017 (สีเทา)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 3290,
                'type_sn' => 1,
                'barcode' => '6901443181698',
                'image' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => '2017-12-28 08:30:29',
                'updated_at' => '2017-12-28 08:32:18',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 3,
            'model' => 'Y7 (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 4990,
                'type_sn' => 1,
                'barcode' => '6901443197729',
                'image' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => '2017-12-28 08:31:29',
                'updated_at' => '2017-12-28 08:32:25',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 3,
            'model' => 'Y3ii (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 2990,
                'type_sn' => 1,
                'barcode' => '6901443123605',
                'image' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'created_at' => '2017-12-28 08:33:55',
                'updated_at' => '2017-12-28 08:36:41',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 3,
            'model' => 'NOVA 2I (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 9990,
                'type_sn' => 1,
                'barcode' => '6901443202232',
                'image' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'created_at' => '2017-12-28 08:36:22',
                'updated_at' => '2017-12-28 08:39:32',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 2,
            'model' => 'F5 YOUTH (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 8990,
                'type_sn' => 1,
                'barcode' => '6944284622098',
                'image' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'created_at' => '2017-12-28 08:38:06',
                'updated_at' => '2017-12-28 08:39:24',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 2,
            'model' => 'A71 (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 5990,
                'type_sn' => 1,
                'barcode' => '6944284620711',
                'image' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'created_at' => '2017-12-28 08:39:16',
                'updated_at' => '2017-12-28 08:42:42',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 2,
            'model' => 'A57 (สีชมพู)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 7990,
                'type_sn' => 1,
                'barcode' => '6944284617735',
                'image' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'created_at' => '2017-12-28 08:40:33',
                'updated_at' => '2017-12-28 08:40:33',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 2,
            'model' => 'A37 (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 4990,
                'type_sn' => 1,
                'barcode' => '6944284619005',
                'image' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'created_at' => '2017-12-28 08:44:04',
                'updated_at' => '2017-12-28 08:44:04',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 1,
            'model' => 'Y53 (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 4990,
                'type_sn' => 1,
                'barcode' => '6935117805436',
                'image' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'created_at' => '2017-12-28 08:45:31',
                'updated_at' => '2017-12-28 08:50:54',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 1,
            'model' => 'Y65 (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 6990,
                'type_sn' => 1,
                'barcode' => '6935117806792',
                'image' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'created_at' => '2017-12-28 08:48:19',
                'updated_at' => '2017-12-28 08:48:19',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 1,
            'model' => 'V5 PLUS (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 10990,
                'type_sn' => 1,
                'barcode' => '6935117804231',
                'image' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'created_at' => '2017-12-28 08:50:18',
                'updated_at' => '2017-12-28 08:50:18',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 5,
            'model' => 'X1 (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 3990,
                'type_sn' => 1,
                'barcode' => '6932438119389',
                'image' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'created_at' => '2017-12-28 08:52:06',
                'updated_at' => '2017-12-28 08:53:37',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 5,
            'model' => 'X1S (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 5990,
                'type_sn' => 1,
                'barcode' => 'X1SGL0717002909',
                'image' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'created_at' => '2017-12-28 08:53:23',
                'updated_at' => '2017-12-28 08:53:23',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 5,
            'model' => 'A1 LITE (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 6990,
                'type_sn' => 1,
                'barcode' => 'A1liteGL0717001583',
                'image' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'created_at' => '2017-12-28 08:56:13',
                'updated_at' => '2017-12-28 08:56:13',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 1,
            'model' => 'V7 + (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 11990,
                'type_sn' => 1,
                'barcode' => '6935117805870',
                'image' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'created_at' => '2017-12-28 08:59:25',
                'updated_at' => '2017-12-28 08:59:25',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 7,
            'model' => 'SUNNY2 PLUS (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 1990,
                'type_sn' => 1,
                'barcode' => '6943279414939',
                'image' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'created_at' => '2017-12-28 09:00:31',
                'updated_at' => '2017-12-28 09:00:31',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 7,
            'model' => 'SUNNY2 PLUS (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 1990,
                'type_sn' => 1,
                'barcode' => '6943279414922',
                'image' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'created_at' => '2017-12-28 09:01:35',
                'updated_at' => '2017-12-28 09:01:35',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 7,
            'model' => 'JERRY2 (สีเทา)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 2590,
                'type_sn' => 1,
                'barcode' => '6943279413482',
                'image' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'created_at' => '2017-12-28 09:02:55',
                'updated_at' => '2017-12-28 09:02:55',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 7,
            'model' => 'LENNY4 PLUS (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 2990,
                'type_sn' => 1,
                'barcode' => '6943279414663',
                'image' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'created_at' => '2017-12-28 09:04:27',
                'updated_at' => '2017-12-28 09:05:48',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 7,
            'model' => 'LENNY4 PLUS (สีเขียวไลม์)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 2990,
                'type_sn' => 1,
                'barcode' => '6943279414687',
                'image' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'created_at' => '2017-12-28 09:05:39',
                'updated_at' => '2017-12-28 09:05:39',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 7,
            'model' => 'LENNY4 PLUS (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 2990,
                'type_sn' => 1,
                'barcode' => '6943279414656',
                'image' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'created_at' => '2017-12-28 09:06:50',
                'updated_at' => '2017-12-28 09:06:50',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 7,
                'model' => 'VIEW',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 4990,
                'type_sn' => 1,
                'barcode' => '6943279414885',
                'image' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'created_at' => '2017-12-28 09:08:06',
                'updated_at' => '2017-12-28 09:08:06',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 7,
            'model' => 'VIEW XL (สีแดงเชอรี่)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 5990,
                'type_sn' => 1,
                'barcode' => '6943279414878',
                'image' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'created_at' => '2017-12-28 09:09:26',
                'updated_at' => '2017-12-28 09:15:41',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 7,
            'model' => 'ROBBY2 (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 3990,
                'type_sn' => 1,
                'barcode' => '6943279414984',
                'image' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'created_at' => '2017-12-28 09:15:32',
                'updated_at' => '2017-12-28 09:15:32',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 10,
                'model' => 'IRIS80',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 1890,
                'type_sn' => 1,
                'barcode' => '306527823413',
                'image' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'created_at' => '2017-12-28 09:16:45',
                'updated_at' => '2017-12-28 09:16:45',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 10,
                'model' => 'IRIS550',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 2990,
                'type_sn' => 1,
                'barcode' => '6933040600678',
                'image' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'created_at' => '2017-12-28 09:18:34',
                'updated_at' => '2017-12-28 09:18:34',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 10,
                'model' => 'IRIS40',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 1890,
                'type_sn' => 1,
                'barcode' => '6933040602375',
                'image' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'created_at' => '2017-12-28 09:21:16',
                'updated_at' => '2017-12-28 09:21:16',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 4,
                'model' => 'KEYSTONE2',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 990,
                'type_sn' => 1,
                'barcode' => '8806086054515',
                'image' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'created_at' => '2017-12-28 09:23:16',
                'updated_at' => '2017-12-28 09:23:16',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 13,
                'model' => 'I-STYLE 7.7',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 1590,
                'type_sn' => 1,
                'barcode' => '8854337011084',
                'image' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'created_at' => '2017-12-28 09:24:09',
                'updated_at' => '2017-12-28 09:24:09',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 8,
                'model' => 'TH1',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 890,
                'type_sn' => 1,
                'barcode' => '8858825000895',
                'image' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'created_at' => '2017-12-28 09:28:32',
                'updated_at' => '2017-12-28 09:34:14',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 1,
            'model' => 'Y55s (สีทอง)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 5990,
                'type_sn' => 1,
                'barcode' => '6935117805061',
                'image' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'created_at' => '2017-12-28 09:29:16',
                'updated_at' => '2017-12-28 09:34:14',
                'product_name' => 'โทรศัพท์',
                'brand_id' => 1,
            'model' => 'Y55s (สีดำ)',
                'category_id' => 1,
                'description' => NULL,
                'amount' => 0,
                'price' => 5990,
                'type_sn' => 1,
                'barcode' => '6935117805887',
                'image' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'created_at' => '2017-12-28 09:44:46',
                'updated_at' => '2017-12-28 09:44:46',
                'product_name' => 'สายไอโฟน+หัวชาร์จ',
                'brand_id' => 14,
                'model' => 'C2',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 270,
                'type_sn' => 0,
                'barcode' => '6957531038504',
                'image' => '/assets/images/products/product-36.jpg',
            ),
            36 => 
            array (
                'id' => 37,
                'created_at' => '2017-12-28 09:49:01',
                'updated_at' => '2017-12-28 09:49:01',
                'product_name' => 'สายไอโฟน+หัวชาร์จ',
                'brand_id' => 14,
                'model' => 'C12',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 390,
                'type_sn' => 0,
                'barcode' => '6957531047766',
                'image' => '/assets/images/products/product-37.jpg',
            ),
            37 => 
            array (
                'id' => 38,
                'created_at' => '2017-12-28 09:51:18',
                'updated_at' => '2017-12-28 09:51:18',
                'product_name' => 'สายชาร์จไอโฟน',
                'brand_id' => 15,
                'model' => 'ET-CX06',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '11113333000024',
                'image' => '/assets/images/products/product-38.jpg',
            ),
            38 => 
            array (
                'id' => 39,
                'created_at' => '2017-12-28 09:56:13',
                'updated_at' => '2017-12-28 09:56:13',
                'product_name' => 'แบตสำรอง 5600 mAh',
                'brand_id' => 12,
                'model' => NULL,
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 390,
                'type_sn' => 0,
                'barcode' => 'A0085682',
                'image' => '/assets/images/products/product-39.jpg',
            ),
            39 => 
            array (
                'id' => 40,
                'created_at' => '2017-12-28 09:58:15',
                'updated_at' => '2017-12-28 09:58:15',
                'product_name' => 'สายชาร์จไอโฟน',
                'brand_id' => 15,
                'model' => 'SA640',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 150,
                'type_sn' => 0,
                'barcode' => '11113333000003',
                'image' => '/assets/images/products/product-40.jpg',
            ),
            40 => 
            array (
                'id' => 41,
                'created_at' => '2017-12-28 10:03:41',
                'updated_at' => '2017-12-28 10:07:47',
                'product_name' => 'หัวชาร์จในรถยนต์ QC3.0',
                'brand_id' => 16,
                'model' => 'ES-KC2',
                'category_id' => 3,
                'description' => 'หัวชาจไว รองรับ Quick Charge 3.0',
                'amount' => 0,
                'price' => 250,
                'type_sn' => 0,
                'barcode' => '6920467900061',
                'image' => '/assets/images/products/product-41.jpg',
            ),
            41 => 
            array (
                'id' => 42,
                'created_at' => '2017-12-28 10:06:14',
                'updated_at' => '2017-12-28 11:00:02',
                'product_name' => 'หัวชาร์จในรถยนต์+สายชาจ',
                'brand_id' => 16,
                'model' => 'ES-158',
                'category_id' => 3,
                'description' => 'สายชาจแอนดรอย์',
                'amount' => 0,
                'price' => 250,
                'type_sn' => 0,
                'barcode' => '6980132577158',
                'image' => '/assets/images/products/product-42.jpg',
            ),
            42 => 
            array (
                'id' => 43,
                'created_at' => '2017-12-28 10:10:19',
                'updated_at' => '2017-12-28 10:10:19',
                'product_name' => 'หัวชาร์จในรถยนต์',
                'brand_id' => 16,
                'model' => 'ES-151',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '6980312956155',
                'image' => '/assets/images/products/product-43.jpg',
            ),
            43 => 
            array (
                'id' => 44,
                'created_at' => '2017-12-28 10:11:23',
                'updated_at' => '2017-12-28 10:11:23',
                'product_name' => 'หัวชาร์จในรถยนต์',
                'brand_id' => 15,
                'model' => 'SC100',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '11113333000004',
                'image' => '/assets/images/products/product-44.jpg',
            ),
            44 => 
            array (
                'id' => 45,
                'created_at' => '2017-12-28 10:12:21',
                'updated_at' => '2017-12-28 10:12:21',
                'product_name' => 'หัวชาร์จในรถยนต์',
                'brand_id' => 15,
                'model' => 'SC150',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '11113333000005',
                'image' => '/assets/images/products/product-45.jpg',
            ),
            45 => 
            array (
                'id' => 47,
                'created_at' => '2017-12-28 11:03:47',
                'updated_at' => '2017-12-28 11:03:47',
                'product_name' => 'หัวชาร์จในรถยนต์',
                'brand_id' => 16,
                'model' => 'ES-138',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '8413135491506',
                'image' => '/assets/images/products/product-47.jpg',
            ),
            46 => 
            array (
                'id' => 48,
                'created_at' => '2017-12-28 11:10:25',
                'updated_at' => '2017-12-28 11:10:25',
                'product_name' => 'สายชาร์จแอนดรอยด์',
                'brand_id' => 16,
                'model' => 'EC-006M',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '8561213549981',
                'image' => '/assets/images/products/product-48.jpg',
            ),
            47 => 
            array (
                'id' => 49,
                'created_at' => '2017-12-28 11:12:42',
                'updated_at' => '2017-12-28 11:12:42',
                'product_name' => 'สายชาร์จแอนดรอยด์',
                'brand_id' => 16,
                'model' => 'ET-I3',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '11113333000027',
                'image' => '/assets/images/products/product-49.jpg',
            ),
            48 => 
            array (
                'id' => 50,
                'created_at' => '2017-12-28 11:14:28',
                'updated_at' => '2017-12-28 11:14:28',
                'product_name' => 'สายชาร์จแอนดรอยด์',
                'brand_id' => 15,
                'model' => NULL,
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 150,
                'type_sn' => 0,
                'barcode' => '11113333000001',
                'image' => '/assets/images/products/product-50.jpg',
            ),
            49 => 
            array (
                'id' => 51,
                'created_at' => '2017-12-28 11:16:09',
                'updated_at' => '2017-12-28 11:16:09',
                'product_name' => 'สายชาร์จ 2IN1',
                'brand_id' => 16,
                'model' => 'ET-SS7',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 180,
                'type_sn' => 0,
                'barcode' => '6980312996007',
                'image' => '/assets/images/products/product-51.jpg',
            ),
            50 => 
            array (
                'id' => 52,
                'created_at' => '2017-12-28 11:18:42',
                'updated_at' => '2017-12-28 11:18:42',
                'product_name' => 'สายชาร์จ 2IN1',
                'brand_id' => 16,
                'model' => 'ET-607',
                'category_id' => 3,
                'description' => 'หัวชาร์จแอนดรอยด์+ไอโฟน',
                'amount' => 0,
                'price' => 180,
                'type_sn' => 0,
                'barcode' => '6980132529607',
                'image' => '/assets/images/products/product-52.jpg',
            ),
            51 => 
            array (
                'id' => 53,
                'created_at' => '2017-12-28 11:20:37',
                'updated_at' => '2017-12-28 11:20:37',
                'product_name' => 'สายชาร์จแอนดรอยด์',
                'brand_id' => 12,
                'model' => 'M-215',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 150,
                'type_sn' => 0,
                'barcode' => '6959556321500',
                'image' => '/assets/images/products/product-53.jpg',
            ),
            52 => 
            array (
                'id' => 54,
                'created_at' => '2017-12-28 11:22:18',
                'updated_at' => '2017-12-28 11:22:18',
                'product_name' => 'สายชาร์จ 2IN1',
                'brand_id' => 16,
                'model' => 'ET-609',
                'category_id' => 3,
                'description' => 'หัวชาร์จแอนดรอยด์+ไอโฟน',
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '8613254964152',
                'image' => '/assets/images/products/product-54.jpg',
            ),
            53 => 
            array (
                'id' => 55,
                'created_at' => '2017-12-28 11:24:32',
                'updated_at' => '2017-12-28 11:24:32',
                'product_name' => 'สายชาร์จ USB-C',
                'brand_id' => 15,
                'model' => NULL,
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 180,
                'type_sn' => 0,
                'barcode' => '11113333000036',
                'image' => '/assets/images/products/product-55.jpg',
            ),
            54 => 
            array (
                'id' => 56,
                'created_at' => '2017-12-28 11:28:39',
                'updated_at' => '2017-12-28 11:28:39',
                'product_name' => 'สายชาร์จ USB-C',
                'brand_id' => 15,
                'model' => 'SA680',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 180,
                'type_sn' => 0,
                'barcode' => '11113333000035',
                'image' => '/assets/images/products/product-56.jpg',
            ),
            55 => 
            array (
                'id' => 57,
                'created_at' => '2017-12-28 11:34:08',
                'updated_at' => '2017-12-28 11:34:08',
                'product_name' => 'ที่วางมือถือในรถยนต์',
                'brand_id' => 12,
                'model' => NULL,
                'category_id' => 5,
                'description' => NULL,
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '11113333000037',
                'image' => '/assets/images/products/product-57.jpg',
            ),
            56 => 
            array (
                'id' => 58,
                'created_at' => '2017-12-28 11:41:34',
                'updated_at' => '2017-12-28 11:41:34',
                'product_name' => 'หัว OTG USB-C',
                'brand_id' => 16,
                'model' => 'ET-OT18',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 99,
                'type_sn' => 0,
                'barcode' => '6980312950818',
                'image' => '/assets/images/products/product-58.jpg',
            ),
            57 => 
            array (
                'id' => 59,
                'created_at' => '2017-12-28 11:43:20',
                'updated_at' => '2017-12-28 11:43:20',
                'product_name' => 'สาย OTG',
                'brand_id' => 16,
                'model' => 'ET-OT04',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 99,
                'type_sn' => 0,
                'barcode' => '6982235110041',
                'image' => '/assets/images/products/product-59.jpg',
            ),
            58 => 
            array (
                'id' => 60,
                'created_at' => '2017-12-28 11:46:03',
                'updated_at' => '2017-12-28 11:46:03',
                'product_name' => 'สาย OTG',
                'brand_id' => 16,
                'model' => 'KS-S06',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 99,
                'type_sn' => 0,
                'barcode' => '4260135509052',
                'image' => '/assets/images/products/product-60.jpg',
            ),
            59 => 
            array (
                'id' => 61,
                'created_at' => '2017-12-28 11:47:42',
                'updated_at' => '2017-12-28 11:47:42',
                'product_name' => 'สายชาร์จ 3IN1',
                'brand_id' => 16,
                'model' => 'EC-IM014',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 200,
                'type_sn' => 0,
                'barcode' => '6862237158152',
                'image' => '/assets/images/products/product-61.jpg',
            ),
            60 => 
            array (
                'id' => 62,
                'created_at' => '2017-12-28 11:49:09',
                'updated_at' => '2017-12-28 11:49:09',
                'product_name' => 'สายชาร์จ 3IN1',
                'brand_id' => 16,
                'model' => 'ET-885',
                'category_id' => 3,
                'description' => NULL,
                'amount' => 0,
                'price' => 250,
                'type_sn' => 0,
                'barcode' => '6980132576885',
                'image' => '/assets/images/products/product-62.jpg',
            ),
        ));
        
        
    }
}